---
:metadata:
  :name: my-build-config-0
  :namespace: my-project-0
  :uid: b6e1c4e7-2528-4c50-8112-e804790680d9
  :resourceVersion: '570011'
  :generation: 2
  :creationTimestamp: '2023-01-09T19:07:04Z'
  :managedFields:
  - :manager: Go-http-client
    :operation: Update
    :apiVersion: build.openshift.io/v1
    :time: '2023-01-09T19:07:04Z'
    :fieldsType: FieldsV1
    :fieldsV1:
      :f:status:
        :f:lastVersion: {}
  - :manager: kubectl-create
    :operation: Update
    :apiVersion: build.openshift.io/v1
    :time: '2023-01-09T19:07:04Z'
    :fieldsType: FieldsV1
    :fieldsV1:
      :f:spec:
        :f:output:
          :f:to: {}
        :f:postCommit:
          :f:script: {}
        :f:runPolicy: {}
        :f:source:
          :f:git:
            :.: {}
            :f:uri: {}
          :f:type: {}
        :f:strategy:
          :f:sourceStrategy:
            :.: {}
            :f:from: {}
          :f:type: {}
        :f:triggers: {}
:spec:
  :triggers:
  - :type: GitHub
    :github:
      :secret: secret101
  - :type: Generic
    :generic:
      :secret: secret101
  :runPolicy: Serial
  :source:
    :type: Git
    :git:
      :uri: https://github.com/openshift/ruby-hello-world
  :strategy:
    :type: Source
    :sourceStrategy:
      :from:
        :kind: DockerImage
        :name: centos/ruby-25-centos7:latest
  :output:
    :to:
      :kind: ImageStreamTag
      :name: origin-ruby-sample:latest
  :resources: {}
  :postCommit:
    :script: bundle exec rake test
  :nodeSelector:
  :successfulBuildsHistoryLimit: 5
  :failedBuildsHistoryLimit: 5
:status:
  :lastVersion: 1
:kind: BuildConfig
:apiVersion: build.openshift.io/v1
